brews:
  - tap:
      owner: riweston
      name: homebrew-tap
      # Optionally a token can be provided, if it differs from the token provided to GoReleaser
      token: "{{ .Env.HOMEBREW }}"
    url_template: "https://github.com/riweston/aztx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy.
    commit_author:
      name: goreleaserbot
      email: goreleaser@riweston.io
    homepage: "https://github.com/riweston/aztx"
    description: "This tool is a helper for azure-cli that leverages fzf for a nice interface to switch between subscription contexts."
    license: "Apache"
    dependencies:
      - name: azure-cli
      - name: fzf
