---
name: "Continuous Deployment: Release"

on:
  push:
    tags:
      - "*"

jobs:
  go-versions:
    name: Lookup go versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: arnested/go-version-action@v1
        id: versions

  goreleaser:
    name: "CD: Release"
    runs-on: ubuntu-latest
    needs: go-versions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.DEPLOY_KEY }}"
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.go-versions.outputs.latest }}
          check-latest: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --config .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW: ${{ secrets.HOMEBREW }}
