---
name: "Continuous Deployment: Release"

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    name: "CD: Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.DEPLOY_KEY }}"
      - uses: arnested/go-version-action@v1
        id: go-version
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.latest }}
          check-latest: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --config .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW: ${{ secrets.HOMEBREW }}
