---
name: "Continuous Deployment: Tagging"

on:
  push:
    branches:
      - master

jobs:
  versionbumper:
    name: "CD: Tagging"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
