---
name: "Continuous Deployment: Tagging"

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
  versionbumper:
    name: "CD: Tagging"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW }}
          WITH_V: false
          RELEASE_BRANCHES: "hotfix.*"
