---
name: "Continuous Deployment: Tagging"

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Continuous Integration: Linting/Go Tests"]
    types: [completed]

jobs:
  versionbumper:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "CD: Tagging"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
