---
name: "Continuous Integration: Build Test Binary (no release)"

on:
  pull_request:
  push:
  workflow_run:
    workflows: ["Continuous Integration: Linting/Go Tests"]
    types: [completed]

jobs:
  goreleaser:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "CI: Build Test Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --config .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW: ${{ secrets.HOMEBREW }}
